### ISSUE TITLE
Create Map & Map Tile components

### ISSUE THREAD

**Issue by ghost-458** [kevinhikaruevans/uojs2#69]

**Comment by kevinhikaruevans** [comment]
@lamo2k123 can you take a look at this branch? https://github.com/kevinhikaruevans/uojs2/compare/get-map-data

I'm trying to send data through the websocket, but I'm getting this error:

> Uncaught SyntaxError: Unexpected token o in JSON at position 1
>     at Object.parse (<anonymous>)
>    at WebSocket.once (transport.js:88)
> once @ transport.js:88

I think it's sending "[object...]" as a string but I'm not sure why. Any ideas? 😕

**Comment by lamo2k123** [comment]
fixed https://github.com/kevinhikaruevans/uojs2/commit/54b3cecad0c58a9b102651de69c077ee7aa56f4a

**Comment by kevinhikaruevans** [comment]
Thanks!

I ran into another issue. I'm trying to use `connect()` on a component, but I'm getting this error:

> Uncaught (in promise) Error: Could not find "store" in either the context or props of "Connect([component] map)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect([component] map)".
>    at invariant (http://localhost:8080/bundle.js:65251:15)
>    at new Connect (http://localhost:8080/bundle.js:70594:58)
>    at http://localhost:8080/bundle.js:98048:24

I'm calling connect in map.js: https://github.com/kevinhikaruevans/uojs2/blob/get-map-data/src/client/components/map/index.js#L13

Should I pass `store` in props from scene/index.js?

(loaded in [scene/index.js](https://github.com/kevinhikaruevans/uojs2/blob/get-map-data/src/client/components/scene/index.js#L48) and in [pages/game/index.js](https://github.com/kevinhikaruevans/uojs2/blob/get-map-data/src/client/pages/game/index.js#L17))

**Comment by lamo2k123** [comment]
The `react-three-renderer` implemented a method that does not render passes React context. And I think that this is not the only problem))
https://github.com/toxicFork/react-three-renderer/blob/master/src/lib/React3Renderer.js#L631

**Comment by lamo2k123** [comment]
Why do not you just THREEJS use?
I think that `react-three-renderer` is not yet a problem.

**Comment by kevinhikaruevans** [comment]
Like... use Three.js without react-three-renderer? I like react-three-renderer because it manages a lot of stuff.

Maybe something like:

* Create React component, connect() to stuff
* In render, create <canvas> element
* Rerender on prop changes?

**Comment by lamo2k123** [comment]
Use the '@connect' component 'scene / index.js' and there Give props to 'map' component.
