### ISSUE TITLE
bindings error

### ISSUE THREAD

**Issue by lamo2k123** [kevinhikaruevans/uojs2#76]
[proxy] $ node src/server -d=* 
[proxy] /var/www/uojs/node_modules/bindings/bindings.js:91
[proxy]   throw err
[proxy]   ^
[proxy] 
[proxy] Error: Could not locate the bindings file. Tried:
[proxy]  → /var/www/uojs/node_modules/uop-hash/build/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/build/Debug/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/build/Release/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/out/Debug/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/Debug/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/out/Release/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/Release/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/build/default/hash.node
[proxy]  → /var/www/uojs/node_modules/uop-hash/compiled/7.2.1/linux/x64/hash.node
[proxy]     at bindings (/var/www/uojs/node_modules/bindings/bindings.js:88:9)
[proxy]     at Object.<anonymous> (/var/www/uojs/node_modules/uop-hash/index.js:1:94)
[proxy]     at Module._compile (module.js:571:32)
[proxy]     at Object.Module._extensions..js (module.js:580:10)
[proxy]     at Module.load (module.js:488:32)
[proxy]     at tryModuleLoad (module.js:447:12)
[proxy]     at Function.Module._load (module.js:439:3)
[proxy]     at Module.require (module.js:498:17)
[proxy]     at require (internal/module.js:20:19)
[proxy]     at Object.<anonymous> (/var/www/uojs/node_modules/uodatareader/map.js:3:14)
[proxy] error Command failed with exit code 1.
[proxy] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lamo2k123** [comment]
oops .. I just did not have python 2
